[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist/spa"

[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true
